spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      auto-commit: false
      schema: ${DATABASE_SCHEMA:project_service}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA:project_service}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DATABASE_SCHEMA:project_service}
    liquibase-schema: ${DATABASE_SCHEMA:project_service}

  data:
      host: ${REDIS_URL:host.docker.internal}
      port: ${REDIS_PORT:6379}
      channel:
        calculations_channel: 
        name: ${REDIS_CALCULATIONS_CHANEL:calculations_channel}

springdoc:
  swagger-ui:
    path: "/documentation.html"
    enabled:  ${SWAGGERUI_ENABLED:true}
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  title: "Project microservice API documentation"
  version: "latest"
  description: "Documentation of end points for project microservice"  

server:
  port: 8082

services:
  minio:
    endpoint:  ${MINIO_SERVICE_HOST:http://localhost:9000}
    access-key: user
    secret-key: password
    bucket-name: corpbucket
    isMocked: false
    max-file-size: 5MB
    target-width: 1080
    target-height: 566

  payment-service:
    host: ${PAYMENT_SERVICE_HOST:http://localhost}
    port: ${PAYMENT_SERVICE_PORT:9080}
  user-service:
    host: ${USER_SERVICE_HOST:http://localhost}
    port: ${USER_SERVICE_PORT:8080}



calculations_messages_processing:
  enabled: true

google:
  calendar:
    application-name: "CorporationX Project Service"
    credentials-json: |
      {
        "type": "service_account",
        "project_id": "corporationx-project-calendar",
        "private_key_id": "private_key_id",
        "private_key": "private_key",
        "client_email": "client_email",
        "client_id": "client_id",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "client_x509_cert_url",
        "universe_domain": "googleapis.com"
      }

logging:
  level:
    root: info
    liquibase: info
    org.testcontainers: info
