spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    hikari:
      auto-commit: false
      schema: ${DATABASE_SCHEMA:project_service}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA:project_service}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DATABASE_SCHEMA:project_service}
    liquibase-schema: ${DATABASE_SCHEMA:project_service}

  data:
    redis:
      host: ${REDIS_URL:host.docker.internal}
      port: ${REDIS_PORT:6379}
      channels:
        calculations_channel:
          name: ${REDIS_CALCULATIONS_CHANEL:calculations_channel}

springdoc:
  swagger-ui:
    path: "/documentation.html"
    enabled: ${SWAGGERUI_ENABLED:true}
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  title: "Project microservice API documentation"
  version: "latest"
  description: "Documentation of end points for project microservice"

server:
  port: ${PROJECT_SERVICE_PORT:8082}

services:
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    access-key: ${S3_ACCESS_KEY:user}
    secret-key: ${S3_SECRET_KEY:password}
    bucket-name: ${S3_BUCKET_NAME:corpbucket}
    region: ${S3_REGION:us-east-1}
    max-file-size: ${S3_MAX_FILE_SIZE:5MB}
    target-width: ${S3_TARGET_WIDTH:1080}
    target-height: ${S3_TARGET_HEIGHT:566}

  payment-service:
    host: ${PAYMENT_SERVICE_HOST:http://localhost}
    port: ${PAYMENT_SERVICE_PORT:9080}
  user-service:
    host: ${USER_SERVICE_HOST:http://localhost}
    port: ${USER_SERVICE_PORT:8080}
  jira:
    base-url: ${JIRA_BASE_URL:}
    username: ${JIRA_USERNAME:}
    password: ${JIRA_PASSWORD:}
    allowed-hosts: ${JIRA_ALLOWED_HOSTS:}

calculations_messages_processing:
  enabled: true



google:
  calendar:
    application-name: "CorporationX Project Service"
    credentials-json: ${GOOGLE_CALENDAR_CREDENTIALS_JSON:}

logging:
  level:
    root: info
    liquibase: info
    org.testcontainers: info
